import {
  Tractors1,
  nh5630,
  tt75t,
  nh8066,
  mf261,
  Tractors6,
  Tractors7,
  Tractors8,
  Tractors9,
  Implements1,
  Implements2,
  Implements3,
  Implements4,
  Spares1,
  Spares2,
  Spares3,
  Spares4,
  bac1,
  bac2,
  bac3,
  bac4,
  pdf1,
  Tractors_PANTUM_CP2200DW,
  Tractors_PANTUM_BM5100FDW,
  Tractors_PANTUM_M6609N,
  Tractors_PANTUM_P3300DN,
  Tractors_PANTUM_P3300DW,
  Tractors_PANTUM_P2509W,
  Tractors_PANTUM_BP5100DN,
  Tractors_PANTUM_M6559N,
  Tractors_PANTUM_P2509,
  hp1,
  hp2,
  hp3,
  ricoh1,
  ricoh2,
  ricoh3,
  ricoh4,
  ricoh5,
  baldan4row,
  tippingtrailer,
} from "../assets/images/";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "/contact",
  },
  {
    _id: 1005,
    title: "News & Promotions",
    link: "/News",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: Tractors1,
    productName: "Tractors",
    price: "35.00",
    Loc: "Uasin Gishu",
    badge: true,
    des: "Call for more Details",
    cat: "Tractors",
  },
  {
    _id: "202",
    img: nh5630,
    productName: "Tractors",
    price: "180.00",
    Loc: "Trans Nzoia",
    badge: true,
    des: "Call for more Details",
    cat: "Tractors",
  },
  {
    _id: "203",
    img: nh8066,
    productName: "Tractors",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Call for more Details",
    cat: "Tractors",
  },
  {
    _id: "204",
    img: mf261,
    productName: "Tractors",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Call for more Details",
    cat: "Tractors",
  },
  {
    _id: "205",
    img: Tractors6,
    productName: "Tractors",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Call for more Details",
    cat: "Tractors",
  },
  {
    _id: "206",
    img: Tractors7,
    productName: "Tractors",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Call for more Details",
    cat: "Tractors",
  },
  {
    _id: "207",
    img: Tractors8,
    productName: "Tractors",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Call for more Details",
    cat: "Tractors",
  },
  {
    _id: "208",
    img: Tractors9,
    productName: "Tractors",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Call for more Details",
    cat: "Tractors",
  },
  {
    _id: "209",
    img: Implements1,
    productName: "Implements",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Call for more Details",
    cat: "Implements",
  },
  {
    _id: "210",
    img: Implements2,
    productName: "Implements",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Call for more Details",
    cat: "Implements",
  },
  {
    _id: "211",
    img: Implements3,
    productName: "Implements",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Call for more Details",
    cat: "Implements",
  },
  {
    _id: "212",
    img: Implements4,
    productName: "Implements",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Call for more Details",
    cat: "Implements",
  },
  {
    _id: "213",
    img: Spares1,
    productName: "Spares",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Call for more Details",
    cat: "Spares",
  },
  {
    _id: "214",
    img: Spares2,
    productName: "Spares",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Call for more Details",
    cat: "Spares",
  },
  {
    _id: "215",
    img: Spares3,
    productName: "Spares",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Call for more Details",
    cat: "Spares",
  },
  {
    _id: "216",
    img: Spares4,
    productName: "Spares",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Call for more Details",
    cat: "Spares",
  },
  {
    _id: "217",
    img: bac1,
    productName: "Cars",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Call for more Details",
    cat: "Bac",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Cars",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Call for more Details",
    cat: "Bac",
  },
  {
    _id: "220",
    img: bac3,
    productName: "Cars",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Call for more Details",
    cat: "Bac",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Cars",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Call for more Details",
    cat: "Bac",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img: Tractors_PANTUM_CP2200DW,
    productName: "nh5630.jpg",
    price: "35.00",
    Loc: "Uasin Gishu",
    badge: true,
    brand: "Pantum",
    des: "Tractors ",
    cat: "Tractors",
    pdf: pdf1,
 
  },
  {
    _id: "202",
    img: Tractors_PANTUM_BM5100FDW,
    productName: "Tractors PANTUM BM5100FDW",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "",
    cat: "Tractors",
    pdf: pdf1,

  },

  {
    _id: "203",
    img: Tractors_PANTUM_BP5100DN,
    productName: "Tractors PANTUM BP5100DN",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
   
  },
  {
    _id: "2005",
    img: Tractors_PANTUM_M6609N,
    productName: "Tractors PANTUM M6559N",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "T",
    cat: "Tractors",
    pdf: pdf1,
   
  },

  {
    _id: "20005",
    img: Tractors_PANTUM_M6559N,
    productName: "Tractors PANTUM M6559N",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
    
  },

  {
    _id: "206",
    img: Tractors_PANTUM_P3300DN,
    productName: "Tractors PANTUM P3300DN",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
    	
  },

  {
    _id: "207",
    img: Tractors_PANTUM_P3300DW,
    productName: "Tractors PANTUM P3300DW",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
    
  },

  {
    _id: "208",
    img: Tractors_PANTUM_P2509W,
    productName: "Tractors PANTUM P2509W",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
    
  },
  {
    _id: "233",
    img: Tractors_PANTUM_P2509,
    productName: "Tractors PANTUM P2509",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
   
  },
  {
    _id: "220",
    img: bac3,
    productName: "Cars",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "",
    cat: "Bac",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Cars",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "",
    cat: "Bac",
  },
  {
    _id: "215",
    img: Spares3,
    productName: "Spares",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "",
    cat: "Spares",
  },
  {
    _id: "216",
    img: Spares4,
    productName: "Spares",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "",
    cat: "Spares",
  },
  {
    _id: "209",
    img: Implements1,
    productName: "Implements",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "",
    cat: "Implements",
  },
  {
    _id: "210",
    img: Implements2,
    productName: "Implements",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "",
    cat: "Implements",
  },

  {
    _id: "211",
    img: Implements3,
    productName: "Implements",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "",
    cat: "Implements",
  },
  {
    _id: "212",
    img: Implements4,
    productName: "Implements",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "",
    cat: "Implements",
  },
  {
    _id: "213",
    img: Spares1,
    productName: "Spares",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "",
    cat: "Spares",
  },
  {
    _id: "214",
    img: Spares2,
    productName: "Spares",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "",
    cat: "Spares",
  },

  {
    _id: "217",
    img: bac1,
    productName: "Cars",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "",
    cat: "Bac",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Cars",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "",
    cat: "Bac",
  },

  // =================== Tractors hp =================

  {
    _id: "hp1",
    img: hp1,
    productName:
      "",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Hp",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
   
  },

  {
    _id: "hp2",
    img: hp2,
    productName: "Tractors HP INK TANK WIRELESS 415 ALL-IN-ONE",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Hp",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
    
  },

  {
    _id: "hp3",
    img: hp3,
    productName: "Tractors HP INK TANK WIRELESS 415 ALL-IN-ONE",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Hp",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
   
  },
  // =================== Tractors ricoh =================
  {
    _id: "ricoh1",
    img: ricoh1,
    productName: "Tractors RICOH P501",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
    
  },

  {
    _id: "ricoh2",
    img: ricoh2,
    productName: "Tractors RICOH SP3710DN",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
   
  },
  {
    _id: "ricoh3",
    img: ricoh3,
    productName: "Tractors RICOH SP4520DN",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
    
  },
  {
    _id: "ricoh4",
    img: ricoh4,
    productName: "Tractors RICOH COULEUR LASER SPC840",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
   
  },
  {
    _id: "ricoh5",
    img: ricoh5,
    productName: "Tractors RICOH SP4510DN (407313)",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Ricoh",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
    
  },

  // =================== Tractors ricoh =================

  {
    _id: "baldan4row",
    img: baldan4row,
    productName: "Tractors EPSON L3251 3EN1 A4 WIFI",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Epson",
    des: "",
    cat: "Tractors",
    pdf: pdf1,
    
  },

  {
    _id: "tippingtrailer",
    img: tippingtrailer,
    productName: "Tipping Used",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "",
    des: "",
    cat: "Implements",
    
    
  },
];
